# Generated by Django 4.0.4 on 2022-05-23 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='name',
            new_name='customer_name',
        ),
        migrations.AlterField(
            model_name='photo',
            name='url',
            field=models.URLField(max_length=350),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Amount'),
        ),
    ]
