# Generated by Django 4.0.4 on 2022-05-24 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_photo_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='name',
            field=models.CharField(default=1, max_length=80),
            preserve_default=False,
        ),
    ]
