# Generated by Django 4.0.3 on 2022-05-24 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_rename_name_booking_customer_name_alter_photo_url_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='equipment',
            new_name='equipments',
        ),
    ]
