# Generated by Django 4.0.3 on 2022-05-24 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_rename_equipment_profile_equipments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='equipments',
            new_name='equipment',
        ),
    ]
