# Generated by Django 4.0.4 on 2022-05-23 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_profile_options_alter_profile_managers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='user',
        ),
    ]
